### ISSUE TITLE
Lost in Backbone Views, Models, Collections, and Templates :(

### ISSUE THREAD

**Issue by econnors** [econnors/talent_rolladex#1]
@harimohanraj89 @DrRobotmck @htella 

The user story I am working on is "AS A EMPLOYER I WANT A LANDING PAGE TO BE ABLE TO VIEW PROFILES"

I have been stuck since 11:00am trying to get my user models to appear on the page.  
My files so far have been pushed.
I have application.js file that makes my user collection and a collectionView
The collectionView grabs the DOM element it will be working on, and loops through all the elements in collection creating a userListView for each model in the collection, which it then appends to the DOM element.
(***I think this is where my problem lies)
userListView creates a DOM element, grabs a template called user-viedo-div, and combines the DOM element to the template.
user-video-div template has the following

<div class="user-image">
  <img src="{{img_url}}" />
</div>
<div class="user-info">
  <h1>
    {{username}}
  </h1>
  <p>
    {{possition}}
  </p>
</div>

I am not getting any console errors but I am seeing in console

 Loaded, bro
New user collection created.
new collection view created
yee haw
child {cid: "view1", collection: child, $el: jQuery.fn.init[1], el: div#collection, constructor: function…}
(2)New User Model

I have seeded my database with two users which the user model is finding.  Where should I look next?

**Comment by harimohanraj89** [comment]
1. Have you tried manually calling the render function on the collection view in the console?
2. Have you double checked your collection listener in your collection view?
3. Have you made sure that when you fetch your collection, you fire a reset event? (`.fetch({reset: true})`)

**Comment by econnors** [comment]
I had my listener in collection view incorrect. Thanks!
