### ISSUE TITLE
Click function to new rails route

### ISSUE THREAD

**Issue by econnors** [econnors/talent_rolladex#2]
@harimohanraj89 @htella @DrRobotmck  You guys are the best!

The user story I am working on is "AS AN EMPLOYER I WANT TO BE ABLE TO CLICK ON A VIDEO SO I CAN GO TO THAT USERS PROFILE VIEW PAGE"

On my collection view I have a click event on each user list view that should run the function showUser.  I am trying to make it so when you do that click event it changes you to the rails show user route, where I will then create a model with that information and views with that model information.  I have gone through homework examples where we create models on the click event, but I cant find any examples in homeworks or on the google machine where the js click event changes the rails route.  I am trying to get to the user show rails route which is currently working.  Pointers please?!

Git has been updated.

**Comment by harimohanraj89** [comment]
So there are two ways to "navigate".

Conventional links (`<a>` tags) will take you from one "Rails route" to another.
Using JS and click events can take you to different Backbone routes, but keep you on the same "Rails route", thus achieving a Single Page Application.

If you want to navigate to a different Rails route, then you should be using conventional links to achieve what you want. There are ways to make JS click events do the same thing, but we can talk about that later if you're interested.

**Comment by econnors** [comment]
I think I will need to talk to you about the additional JS way because of what I am trying to make my app accomplish.  I don't want a link tag on the page, i want the div the information is in to be the link, similar to my first project.
