### ISSUE TITLE
Problem loading json for user/:id when switching from backbone to rails route

### ISSUE THREAD

**Issue by econnors** [econnors/talent_rolladex#3]
@harimohanraj89 @htella @DrRobotmck 

The user story I am back to working on is "AS AN EMPLOYER I WANT TO BE ABLE TO CLICK ON A VIDEO TO GO TO THAT USERS PROFILE VIEW PAGE".

My home page is my user/index page.  On it is a collection view with model views.  When you click on the model it takes you to the user/show page.  If you manually type in this route i.e. localhost:3000/users/1 it shows the skills and projects for that user.  This information is got from AJAX requests.  However, when you go to the user/show page from clicking on the model view it doesn't render the skills or projects information.

Help please. :)

**Comment by DrRobotmck** [comment]
Take a look at this: [Turbolinks in Rails](http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links)

**Comment by DrRobotmck** [comment]
What have you tried to do? What does your server look like? Is there a request going through?
