### ISSUE TITLE
backbone search view

### ISSUE THREAD

**Issue by econnors** [econnors/talent_rolladex#4]
@harimohanraj89 @htella @DrRobotmck 

The user story I am working on is "AS A EMPLOYER I WANT TO TYPE IN A POSSITION IN THE SEARCH BAR SO THAT I CAN FILTER THE USER PROFILES I GET BACK"

I have a search view and a collection view which has a bunch of model views.  
my search view:

events: {
	'click button':'search'
},

search: function(){
	var searchWord = escape($('#search-input').val());
	App.collection.fetchByTerm(searchWord);
}

The error message I am getting is: "Uncaught TypeError: Cannot read property 'fetchByTerm' of undefined".

**Comment by econnors** [comment]
Actually the search function is working but it is not effecting the rendered collection view

**Comment by htella** [comment]
got this one

**Comment by htella** [comment]
line 18 in collectionSearchView.js

``App.collection.fetchByTerm(searchWord);``

Is there such a thing as App.collection

**Comment by econnors** [comment]
sorry i didnt update the files.  I have:

App.users.fetch({possition: searchWord});
