### ISSUE TITLE
API to my database help

### ISSUE THREAD

**Issue by econnors** [econnors/talent_rolladex#5]
@harimohanraj89 @htella @DrRobotmck 

The user story I am working on is "AS A USER I WANT TO BE ABLE TO RECORD A SMALL INTERVIEW VIDEO" and "AS A USER I WANT TO BE ABLE TO CREATE A PROFILE TO SHOWCASE MY TALENT" which is using the Ziggeo API.  With this api you access every video with a video token that is attached to it when you create the video.  I want to be able to add that video token to the user database so when you click on there profile it accesses that video.  I am confused how to save that videotoken to my database.  I guess i just need a refresher on the rails create path.

**Comment by htella** [comment]
ok great lets talk

**Comment by DrRobotmck** [comment]
is this resolved?

**Comment by econnors** [comment]
I was helping Amanda, but I am ready now.

**Comment by DrRobotmck** [comment]
What have you tried so far?

**Comment by econnors** [comment]
Actually nevermind, I think I found a new way to save the keys

**Comment by harimohanraj89** [comment]
Post the code that is communicating with the Ziggeo API and producing the token that you need to save. Are you communicating with Ziggeo through JS or Ruby?

**Comment by econnors** [comment]
Ruby

ON appliction.html.erb


  <link rel="stylesheet" href="//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" />
	<script src="//assets.ziggeo.com/js/ziggeo-jquery-json2-betajs-player.min.js"></script>
	<script>ZiggeoApi.token = "<%= ENV['ZIGGEO_TOKEN'] %>";</script>

ON new.html.erb

<div id="video-recorder">
	<p>Record your video</p>
	<ziggeo ziggeo-width=550 ziggeo-height=400 ziggeo-input_bind='videotoken' type='hidden'></ziggeo>
</div>

ON user controller

def new
	@user = User.new
	# @videotoken = params[:videotoken]
	render :new
end

def create
	@user = User.new(user_params)
	# videoToken = {params[:videotoken]}
	# render json: User.create(user_params)
end
